- name: Demo on loops
  hosts: localhost
  tasks:
    - name: Print debug
      ansible.builtin.debug:
        msg: Hello World
      loop:
        - apple
        - banana
        - orange
        - mango